### ISSUE TITLE
Portfolio Review

### ISSUE THREAD

**Issue by LindaEng** [VicBriar/Portfolio#14]
### Portfolio Review
First off, congratulations on assembling such a wonderful portfolio! Your projects showcase a broad spectrum of skills and experiences in software development, exemplifying your dedication to learning and professional growth. To further enhance your portfolio and address specific job function gaps, I've reviewed your projects against a comprehensive software engineering rubric. This analysis has helped identify areas where additional documentation or project enhancements could further demonstrate your competencies, particularly in areas not fully covered by your existing projects.

Below is a chart summarizing the competencies demonstrated across your projects, marked with an 'X'. It's designed to provide a clear overview of where your strengths are most evident, as well as highlight opportunities for growth. The goal here isn't to underline what's missing but rather to spotlight areas for potential enrichment that could make your portfolio even more impressive.

Following the chart, you'll find suggestions aimed at filling in some of the gaps related to specific job functions. These recommendations are tailored to encourage independent work on your current repositories, ensuring that you can continue to grow and showcase your abilities without the need for collaborative projects or new partners. 💯 

| Competency                          | SGANBL | Portfolio Site | Old Portfolio | GamerPointsApp | Inventory App | Enterprise Work |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 1.1 SLDCStages                   |        |                |               |                |               | Suggested       |
| JF 1.2 SLDCRoles                    |        |                |               |                |               |                 |
| JF 1.3 OrgLifeCycle                 |        |                |               |                |               |                 |
| JF 1.4 DevMethodologies             | X      | X              | X             |                | X             |                 |
| JF 1.5 EffectiveTeamWork            |        |                | X             |                |               |                 |
| JF 1.6 Curiosity                    | X      |                |               |                |               |                 |
| JF 1.7 Creativity                   | X      |                |               |                |               |                 |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 2.1 OrgPolicies                  |        |                |               | X              |               |                 |
| JF 2.2 UseCases                     | X      |                |               |                |               |                 |
| JF 2.3 LogicalThinking              | X      |                |               |                |               |                 |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 3.1 ReusableSolutions            |        |                |               | X              | X             | Suggested       |
| JF 3.2 ReadSpecifications           |        |                |               |                |               |                 |
| JF 3.3 UserInterfaces               | X      |                |               |                |               |                 |
| JF 3.4 SoftwareDesigns              | X      |                |               | X              | X             |                 |
| JF 3.5 TechSpecs                    |        |                |               |                |               |                 |
| JF 3.6 ProfessionalEnvironment      |        |                |               |                |               |                 |
| JF 3.7 Integrity                    |        |                |               |                |               |                 |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 4.1 AlgorithmicPrinciples        |        |                |               |                |               | Suggested       |
| JF 4.2 Databases                    |        |                |               |                |               |                 |
| JF 4.3 Datasets                     |        |                |               |                |               |                 |
| JF 4.4 MaintainCodeBase             |        |                |               |                |               |                 |
| JF 4.5 DeployCode                   |        |                |               |                |               | X               |
| JF 4.6 ApplyParadigms               |        |                |               |                |               |                 |
| JF 4.7 ApplyAlgorithms              |        |                |               |                |               |                 |
| JF 4.8 InterpretDesigns             | X      | X              | X             |                | X             |                 |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 5.1 SoftwareTesting              | X      | X              | X             | X              |               |                 |
| JF 5.2 AnalyzeErrors                |        |                |               |                |               | X               |
| JF 5.3 ConductTests                 |        |                |               |                |               | X               |
| JF 5.4 TestScenarios                |        |                |               |                |               |                 |
| JF 5.5 Debugging                    | X      | X              | X             |                |               |                 |
| JF 5.6 TestingFrameworks            |        |                |               |                |               |                 |
|-------------------------------------|--------|----------------|---------------|----------------|---------------|-----------------|
| JF 6.1 CommunicationMethods         |        |                |               |                |               |                 |
| JF 6.2 VersionControl               |        |                |               |                | X             | X               |
| JF 6.3 CommunicateSolutions         |        |                |               |                |               |                 |
| JF 6.4 Independent                  |        |                |               |                |               | X               |
| JF 6.5 Collaboration                |        |                |               |                |               |                 |
| JF 6.6 Initiative                   |        |                |               |                |               |                 |
| JF 6.7 CommunicateEffectively       | X      | X              |               |                |               |                 |

### Unsatisfied Job Functions and Suggestions

**JOB FUNCTION 1: Plan a Set of Software Development Requirements**

JF 1.1 SLDCStages: On your GitHub repository for any of your projects, add detailed documentation to the README or Wiki section that outlines the stages of the Software Development Life Cycle (SDLC) you followed. For each stage (e.g., Requirements Gathering, Design, Implementation, Testing, Deployment, Maintenance), describe what actions you took, challenges faced, and how you overcame them. This will demonstrate your understanding and application of SDLC stages in a project.

**JOB FUNCTION 4: Write and Implement a Logical and Maintainable Software Solution**

JF 4.1 AlgorithmicPrinciples: Choose a feature or function in one of your projects that could benefit from optimization. Implement a more sophisticated algorithm that improves performance, scalability, or efficiency. In your repository, add a section in the README or a separate documentation file that describes the original state, the changes made, the algorithmic principles applied, and the impact on the project's performance. Use code snippets, before-and-after benchmarks, and any relevant links to studies or resources that influenced your approach.

**Comment by VicBriar** [comment]
- [x] **JOB function 1:** feedback addressed here:
* https://github.com/VicBriar/Portfolio/pull/16 

- [ ] **JOB function 4:**
